### ISSUE TITLE
unable to use mixed precision

### ISSUE THREAD

**Issue by callzhang** [hankcs/HanLP#1592]
**Describe the bug**
Unable to use automatic mixed precision

**Code to reproduce the issue**

```
if self.config.use_amp:
     policy = mixed_precision.Policy('mixed_float16')
     mixed_precision.set_policy(policy)
```

**Describe the current behavior**
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/lei/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/lei/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/lei/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/lei/Documents/Projects/NLP/新华社NLP/分类/hanlp_classification.py", line 42, in <module>
    history = classifier.fit(TRANIN_SET, DEV_SET, save_dir, **kwargs)
  File "/Users/lei/Documents/Projects/NLP/HanLP/hanlp/components/classifiers/transformer_classifier.py", line 119, in fit
    return super().fit(**merge_locals_kwargs(locals(), kwargs))
  File "/Users/lei/Documents/Projects/NLP/HanLP/hanlp/common/component.py", line 341, in fit
    model, optimizer, loss, metrics = self.build(**merge_dict(self.config, logger=logger, training=True))
  File "/Users/lei/Documents/Projects/NLP/HanLP/hanlp/common/component.py", line 255, in build
    self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
  File "/Users/lei/Documents/Projects/NLP/HanLP/hanlp/components/classifiers/transformer_classifier.py", line 174, in build_model
    model, self.transform.tokenizer = build_transformer(transformer, max_length, len(self.transform.label_vocab),
  File "/Users/lei/Documents/Projects/NLP/HanLP/hanlp/layers/transformers/loader.py", line 66, in build_transformer
    output = l_bert([l_input_ids, l_token_type_ids], mask=l_mask_ids)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /usr/local/lib/python3.8/site-packages/bert/model.py:79 call  *
        embedding_output = self.embeddings_layer(inputs, mask=mask, training=training)
    /usr/local/lib/python3.8/site-packages/bert/embeddings.py:226 call  *
        embedding_output += tf.reshape(pos_embeddings, broadcast_shape)
    /usr/local/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py:1141 binary_op_wrapper
        raise e
    /usr/local/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py:1125 binary_op_wrapper
        return func(x, y, name=name)
    /usr/local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py:1447 _add_dispatch
        return gen_math_ops.add_v2(x, y, name=name)
    /usr/local/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py:495 add_v2
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /usr/local/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:503 _apply_op_helper
        raise TypeError(

    TypeError: Input 'y' of 'AddV2' Op has type float16 that does not match type float32 of argument 'x'.
```

**Expected behavior**
amp mode enabled

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Python version: 3.8
- HanLP version: LATEST

**Other info / logs**

* [x] I've completed this form and searched the web for solutions.

**Comment by hankcs** [comment]
Maybe one upgrade of TF broke this feature. Could you try out the solutions listed in https://github.com/tensorflow/tensorflow/issues/34406 ?

**Comment by callzhang** [comment]
After debugging I found it is related to the package `bert-for-tf2`. This package also created another issue related to custom loss function from tfa. Have you think if using `huggingface` instead of `bert-for-tf2`?

**Comment by hankcs** [comment]
> After debugging I found it is related to the package `bert-for-tf2`. This package also created another issue related to custom loss function from tfa. Have you think if using `huggingface` instead of `bert-for-tf2`?

Yes, I was using `huggingface ` for the  initial 2.0 release but its downloading speed was too slow so I switched to that one. Now they have a fast global CDN and I've been heavily using theirs in 2.1. Please wait for a couple of days, I'll release 2.1 soon.

**Comment by callzhang** [comment]
I tried huggingface but still got the same error. It's very easy to reproduce these two errors:
1. use_amp
2. use tfa.losses.SigmoidFocalCrossEntropy()
Can you take a look?

**Comment by hankcs** [comment]
I can't find your codes using huggingface in https://github.com/hankcs/HanLP/pull/1595/files .
I don't think using `tfa` is a good idea. It's kind of a community supported package and tends to be buggy. I've encountered several glitches using their CRF implementation. 
huggingface team confirmed this error is resolved in https://github.com/huggingface/transformers/issues/3320#issuecomment-730073845 so please make sure you are using the latest version.

**Comment by Jet-Shawn** [comment]
I‘ve tried to upgrade hanlp in the anaconda prompt, but it still showed that **cannot import name 'albert_models_tfhub'** . Please help me to solve this problem. Thx a lot! :)

**Comment by Jet-Shawn** [comment]
Traceback (most recent call last):
  File "F:\Program_Files\Anaconda3\envs\tensorflow-gpu\lib\site-packages\hanlp-2.1.0a12-py3.6.egg\hanlp\utils\component_util.py", line 74, in load_from_meta_file
    obj: Component = object_from_classpath(cls)
  File "F:\Program_Files\Anaconda3\envs\tensorflow-gpu\lib\site-packages\hanlp_common-0.0.4-py3.6.egg\hanlp_common\reflection.py", line 27, in object_from_classpath
    classpath = str_to_type(classpath)
  File "F:\Program_Files\Anaconda3\envs\tensorflow-gpu\lib\site-packages\hanlp_common-0.0.4-py3.6.egg\hanlp_common\reflection.py", line 44, in str_to_type
    cls = getattr(importlib.import_module(module_name), class_name)
  File "F:\Program_Files\Anaconda3\envs\tensorflow-gpu\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\Program_Files\Anaconda3\envs\tensorflow-gpu\lib\site-packages\hanlp-2.1.0a12-py3.6.egg\hanlp\components\tok_tf.py", line 12, in <module>
    from hanlp.components.taggers.transformers.transformer_tagger_tf import TransformerTaggerTF
  File "F:\Program_Files\Anaconda3\envs\tensorflow-gpu\lib\site-packages\hanlp-2.1.0a12-py3.6.egg\hanlp\components\taggers\transformers\transformer_tagger_tf.py", line 11, in <module>
    from hanlp.layers.transformers.loader_tf import build_transformer
  File "F:\Program_Files\Anaconda3\envs\tensorflow-gpu\lib\site-packages\hanlp-2.1.0a12-py3.6.egg\hanlp\layers\transformers\loader_tf.py", line 9, in <module>
    from bert import albert_models_tfhub, fetch_tfhub_albert_model, load_stock_weights
ImportError: cannot import name 'albert_models_tfhub'

**Comment by hankcs** [comment]
Sorry for the delay. This bug has been addressed in the latest TensorFlow release. Thanks.
